# Generated by Django 5.2.8 on 2025-11-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(max_length=130, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='slug',
            field=models.SlugField(max_length=130, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
