# Generated by Django 5.2.8 on 2025-11-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_categoria_slug_productos_slug_alter_categoria_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('textil', 'Textil'), ('taza', 'Taza'), ('filamento', 'Filamento 3D'), ('vinilo', 'Vinilo'), ('tinta', 'Tinta'), ('papeleria', 'Papelería'), ('empaque', 'Cajas'), ('otro', 'Otro')], max_length=30)),
                ('cantidad', models.PositiveIntegerField()),
                ('unidad', models.CharField(blank=True, choices=[('mts', 'Metros'), ('cms', 'Centímetros'), ('kg', 'Kilogramos'), ('gr', 'Gramos'), ('Lts', 'Litros'), ('pliegos', 'Pliegos'), ('cc', 'Centímetros Cúbicos'), ('ml', 'Mililitros'), ('unidades', 'Unidades'), ('otro', 'Otro')], max_length=30)),
                ('marca', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('negro', 'Negro'), ('amarillo', 'Amarillo'), ('azul', 'Azul'), ('blanco', 'Bolanco'), ('verde', 'Verde'), ('rojo', 'Rojo'), ('naranja', 'Naranja'), ('morado', 'Morado'), ('otro', 'Otro')], max_length=20)),
            ],
        ),
    ]
