# Generated by Django 5.2.8 on 2025-12-01 21:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_insumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=120)),
                ('correo_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_producto', models.PositiveIntegerField()),
                ('pedido_img_1', models.ImageField(blank=True, null=True, upload_to='pedidos/')),
                ('pedido_img_2', models.ImageField(blank=True, null=True, upload_to='pedidos/')),
                ('pedido_img_3', models.ImageField(blank=True, null=True, upload_to='pedidos/')),
                ('plataforma', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('presencial', 'Presencial'), ('web', 'Página Web'), ('otro', 'Otro')], max_length=30)),
                ('estado_pedido_actual', models.CharField(choices=[('solicitado', 'Solicitado'), ('aprobado', 'Aprobado'), ('en_proceso', 'En proceso'), ('realizada', 'Realizada'), ('entregada', 'Entregada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], max_length=30)),
                ('estado_pago_actual', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], max_length=30)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('notas_adicionales', models.TextField(blank=True, null=True)),
                ('token_seguimiento', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('producto_requerido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.productos')),
            ],
        ),
    ]
