# Generated by Django 5.2.8 on 2025-12-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='slug',
            field=models.SlugField(max_length=130, null=True, unique=True),
        ),
    ]
