# Generated by Django 5.2.8 on 2025-12-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_insumo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pago_actual',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido_actual',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('aprobado', 'Aprobado'), ('en_proceso', 'En proceso'), ('realizada', 'Realizada'), ('entregada', 'Entregada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='solicitado', max_length=30),
        ),
    ]
