# Generated by Django 5.2.8 on 2025-12-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_pedido_estado_pago_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='es_destacado',
            field=models.BooleanField(default=False),
        ),
    ]
