# Generated by Django 5.2.8 on 2025-12-14 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_productos_es_destacado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('asunto', models.CharField(choices=[('consulta_general', 'Consulta General'), ('soporte_tecnico', 'Soporte Técnico'), ('problemas_con_pedido', 'Problemas con el Pedido'), ('problemas_de_pago', 'Problemas de Pago'), ('problemas_de_envio', 'Problemas de Envío'), ('pedido_no_recibido', 'Pedido No Recibido'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('otro', 'Otro')], max_length=250)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('respondido', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
